apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "nutriai.commonLabels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
